### ISSUE TITLE
Investigate cookies support

### ISSUE THREAD

**Issue by klouvas** [SokratisVidros/apicco#24]
It seems that cookies are not being sent due to the following quote and current implementation of `apicco-sdk`:
>fetch won’t send cookies, unless you set the credentials init option. (Since Aug 25, 2017. The spec changed the default credentials policy to same-origin. Firefox changed since 61.0b13.)
see: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

We should validate that the fix (adding `credentials` in `init`) does not break sdk in node apps.

**Comment by DimitrK** [comment]
The issue is not client-side only, nor Apicco only but requires server changes as well on each service wishes to track the visitor. The reason for not tracking the visitor cookie is indeed due to the missing credentials which Apicco library doesn’t send to the server. Although this could be added in the library by sending `credentials: include` on each XHR request, at its current state the execution would throw an error on runtime disallowing any requests to be made on the web services Apicco would integrated with. 

The reason is that CORS prevents XHR requests for sending client credentials by default and services may be on different origin than the client. This is the case with most if not all of the services we use Apicco for. 

In order to work properly, each service needs to allow this method by sending the corresponding header `Access-Control-Allow-Credentials`. This is why it could not be client-side only change and since Apicco as a library should be agnostic of the client it runs to, I can’t think of alternatives like checking any specific client cookies and send its values to some custom header.

The solution proposed on that has two parts:

- For Apicco to remain agnostic
  Use  `/discovery` endpoint as a server CORS sniffing mechanism. The response of the server would reveal any `Access-Control-*` headers, then save the values of that headers as `meta` flags in Apicco state. Later use these value for subsequent requests and conditionally include or not the credentials option in that requests. 

  So for example if a header for `Access-Control-Allow-Credentials` is set to `true`, it will be sent in response to `/discovery` request, then use `credentials: 'include'` on subsequent apicco client requests which the browser would now permit.

- For services compatible with apicco 

  - enable the `Access-Control-Allow-Credentials` 

  - enable the `Access-Control-Expose-Headers`  ([info](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers)) to expose the credentials header on fetch response headers object.

**Pros**:

- Is backwards compatible on browsers, meaning the requests wont be made with credentials option if no cors headers detected, so no fear of breaking the client

- Is backwards compatible on server side when Apicco SDK is used as a back-end library. Ending up making requests with credentials: include, isomorphic-fetch omits this option on server environments

**Cons**:

- Beside the credentials header, it requires an extra header to be set on the back end: Access-Control-Expose-Headers: Access-Control-Allow-Credentials

**Comment by klouvas** [comment]
another **cons** is that in `discovery` endpoint the `visitor` cookie will not be logged.

**Comment by DimitrK** [comment]
Yeap! But with this request being a generic library request, not within the application domain, is it needed there such info?

**Comment by SokratisVidros** [comment]
It would be good to describe how to enable that and use the __meta object.
